# Generated by Django 3.0.6 on 2020-05-20 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=45)),
                ('Middle_Name', models.CharField(default='-', max_length=45, null=True)),
                ('Last_Name', models.CharField(max_length=67)),
                ('Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(default='-', max_length=600, null=True)),
                ('Email', models.EmailField(default='-', max_length=254, null=True)),
                ('Mobile_No', models.CharField(default='-', max_length=10)),
                ('Permanent_Add', models.CharField(max_length=100)),
                ('City', models.CharField(default='Siliguri', max_length=30)),
                ('States', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('state', 'Arunachal Pradesh(Itanagar)'), ('state', 'Assam(Dispur)'), ('state', 'Bihar(Patna)'), ('state', 'Chhattisgarh(Raipur)'), ('state', 'Goa(Panaji)'), ('state', 'Gujarat(Gandhinagar)'), ('state', 'Haryana(Chandigarh))'), ('state', 'Himachal Pradesh(Shimla)'), ('state', 'Jharkhand(Ranchi)'), ('state', 'Karnataka(Bangalore)'), ('state', 'Kerala(Thiruvananthapuram)'), ('state', 'Madhya Pradesh(Bhopal)'), ('state', 'Maharashtra(Mumbai)'), ('state', 'Manipur(Imphal)'), ('state', 'Meghalaya(Shillong)'), ('state', 'Mizoram(Aizawl)'), ('state', 'Nagaland(Kohima)'), ('state', 'Odisha(Bhubaneshwar)'), ('state', 'Punjab(Chandigarh)'), ('state', 'Rajasthan(Jaipur)'), ('state', 'Sikkim(Gangtok)'), ('state', 'Tamil Nadu(Chennai)'), ('state', 'Telangana(Hyderabad)'), ('state', 'Tripura(Agartala)'), ('state', 'Uttarakhand(Dehradun)'), ('state', 'Uttar Pradesh(Lucknow)'), ('state', 'West Bengal(Kolkata)'), ('union territories', ' Andaman and Nicobar Islands(Port Blair)'), ('union territories', ' Chandigarh(Chandigarh)'), ('union territories', 'Dadra and Nagar Haveli and Daman & Diu'), ('union territories', 'The Government of NCT of Delhi(Delhi)'), ('union territories', ' Jammu & Kashmir(Srinagar-S*, Jammu-W*)'), ('union territories', 'Ladakh(Leh)'), ('union territories', 'Lakshadweep(Kavaratti)'), ('union territories', ' Puducherry(Puducherry)')], default='West Bengal(Kolkata)', max_length=30)),
                ('Country', models.CharField(default='India', max_length=30)),
                ('Photo', models.ImageField(default='-', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('individual', 'individual'), ('HUF', 'HUF'), ('Company', 'Company'), ('Firm', 'Firm'), ('AOP', 'AOP'), ('Local authority', 'Local authority'), ('Artificial juridicial person', 'Artificial juridicial person'), ('Others', 'Others')], max_length=30)),
                ('Title', models.CharField(default='-', max_length=30, null=True)),
                ('Name', models.CharField(default='-', max_length=30)),
                ('Pan', models.CharField(default='-', max_length=10)),
                ('First_Name', models.CharField(default='-', max_length=20)),
                ('Last_Name', models.CharField(default='-', max_length=20)),
                ('Date_of_Birth', models.DateField(default='2020-01-01')),
                ('Flat_no', models.CharField(default='-', max_length=10, null=True)),
                ('Name_of_Premises', models.CharField(default='-', max_length=20, null=True)),
                ('Road', models.CharField(default='-', max_length=30, null=True)),
                ('Area', models.CharField(default='-', max_length=40, null=True)),
                ('City', models.CharField(default='Siliguri', max_length=50)),
                ('States', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('state', 'Arunachal Pradesh(Itanagar)'), ('state', 'Assam(Dispur)'), ('state', 'Bihar(Patna)'), ('state', 'Chhattisgarh(Raipur)'), ('state', 'Goa(Panaji)'), ('state', 'Gujarat(Gandhinagar)'), ('state', 'Haryana(Chandigarh))'), ('state', 'Himachal Pradesh(Shimla)'), ('state', 'Jharkhand(Ranchi)'), ('state', 'Karnataka(Bangalore)'), ('state', 'Kerala(Thiruvananthapuram)'), ('state', 'Madhya Pradesh(Bhopal)'), ('state', 'Maharashtra(Mumbai)'), ('state', 'Manipur(Imphal)'), ('state', 'Meghalaya(Shillong)'), ('state', 'Mizoram(Aizawl)'), ('state', 'Nagaland(Kohima)'), ('state', 'Odisha(Bhubaneshwar)'), ('state', 'Punjab(Chandigarh)'), ('state', 'Rajasthan(Jaipur)'), ('state', 'Sikkim(Gangtok)'), ('state', 'Tamil Nadu(Chennai)'), ('state', 'Telangana(Hyderabad)'), ('state', 'Tripura(Agartala)'), ('state', 'Uttarakhand(Dehradun)'), ('state', 'Uttar Pradesh(Lucknow)'), ('state', 'West Bengal(Kolkata)'), ('union territories', ' Andaman and Nicobar Islands(Port Blair)'), ('union territories', ' Chandigarh(Chandigarh)'), ('union territories', 'Dadra and Nagar Haveli and Daman & Diu'), ('union territories', 'The Government of NCT of Delhi(Delhi)'), ('union territories', ' Jammu & Kashmir(Srinagar-S*, Jammu-W*)'), ('union territories', 'Ladakh(Leh)'), ('union territories', 'Lakshadweep(Kavaratti)'), ('union territories', ' Puducherry(Puducherry)')], default='West Bengal(Kolkata)', max_length=30)),
                ('Country', models.CharField(default='India', max_length=20)),
                ('Pin_Code', models.CharField(default='-', max_length=6, null=True)),
                ('Email_Address', models.EmailField(default='-', max_length=254, null=True)),
                ('Mobile_no', models.CharField(default='-', max_length=10)),
                ('GST', models.CharField(default='-', max_length=15, null=True)),
                ('Aadhar_no', models.CharField(default='-', max_length=12, null=True)),
                ('TDS_no', models.CharField(default='-', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='-', max_length=30, null=True)),
                ('Description', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='-', max_length=45, null=True)),
                ('Middle_Name', models.CharField(default='-', max_length=45, null=True)),
                ('Last_Name', models.CharField(default='-', max_length=67, null=True)),
                ('Name', models.CharField(default='-', max_length=50, null=True)),
                ('Designation', models.CharField(default='-', max_length=600, null=True)),
                ('Email', models.EmailField(default='-', max_length=254, null=True)),
                ('Mobile_No', models.CharField(default='-', max_length=10, null=True)),
                ('City', models.CharField(max_length=30)),
                ('States', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('state', 'Arunachal Pradesh(Itanagar)'), ('state', 'Assam(Dispur)'), ('state', 'Bihar(Patna)'), ('state', 'Chhattisgarh(Raipur)'), ('state', 'Goa(Panaji)'), ('state', 'Gujarat(Gandhinagar)'), ('state', 'Haryana(Chandigarh))'), ('state', 'Himachal Pradesh(Shimla)'), ('state', 'Jharkhand(Ranchi)'), ('state', 'Karnataka(Bangalore)'), ('state', 'Kerala(Thiruvananthapuram)'), ('state', 'Madhya Pradesh(Bhopal)'), ('state', 'Maharashtra(Mumbai)'), ('state', 'Manipur(Imphal)'), ('state', 'Meghalaya(Shillong)'), ('state', 'Mizoram(Aizawl)'), ('state', 'Nagaland(Kohima)'), ('state', 'Odisha(Bhubaneshwar)'), ('state', 'Punjab(Chandigarh)'), ('state', 'Rajasthan(Jaipur)'), ('state', 'Sikkim(Gangtok)'), ('state', 'Tamil Nadu(Chennai)'), ('state', 'Telangana(Hyderabad)'), ('state', 'Tripura(Agartala)'), ('state', 'Uttarakhand(Dehradun)'), ('state', 'Uttar Pradesh(Lucknow)'), ('state', 'West Bengal(Kolkata)'), ('union territories', ' Andaman and Nicobar Islands(Port Blair)'), ('union territories', ' Chandigarh(Chandigarh)'), ('union territories', 'Dadra and Nagar Haveli and Daman & Diu'), ('union territories', 'The Government of NCT of Delhi(Delhi)'), ('union territories', ' Jammu & Kashmir(Srinagar-S*, Jammu-W*)'), ('union territories', 'Ladakh(Leh)'), ('union territories', 'Lakshadweep(Kavaratti)'), ('union territories', ' Puducherry(Puducherry)')], default='West Bengal(Kolkata)', max_length=30)),
                ('Country', models.CharField(default='India', max_length=30)),
                ('Photo', models.ImageField(default='Null', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='-', max_length=90)),
                ('Duration', models.DurationField()),
                ('Specify_Due_Date', models.DateField(default='2020-01-01')),
                ('Set_Reminder_From', models.DurationField()),
                ('department', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='demoapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='-', max_length=60)),
                ('Stage', models.CharField(default='-', max_length=70, null=True)),
                ('Assign_to', models.CharField(default='-', max_length=90)),
                ('Group_Member', models.CharField(default='-', max_length=90)),
                ('Team_lead', models.CharField(default='-', max_length=40, null=True)),
                ('Create_date', models.DateField(default='2020-01-01')),
                ('Est_finish_date', models.DateField(default='2020-01-01')),
                ('Actual_Start', models.DurationField(default='2020-01-01')),
                ('Actual_Complete', models.DurationField(default='2020-01-01')),
                ('Comments', models.CharField(default='-', max_length=800, null=True)),
                ('worklog', models.CharField(default='-', max_length=40, null=True)),
                ('Description', models.CharField(default='-', max_length=600, null=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Client')),
                ('Department', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='demoapp.Department')),
                ('Work', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='demoapp.Work')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='-', max_length=50)),
                ('Industry', models.CharField(default='-', max_length=45, null=True)),
                ('Email', models.EmailField(default='-', max_length=254)),
                ('Phone', models.CharField(default='-', max_length=10)),
                ('Type', models.CharField(default='-', max_length=70, null=True)),
                ('Permanent_Add', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(default='Siliguri', max_length=30)),
                ('States', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('state', 'Arunachal Pradesh(Itanagar)'), ('state', 'Assam(Dispur)'), ('state', 'Bihar(Patna)'), ('state', 'Chhattisgarh(Raipur)'), ('state', 'Goa(Panaji)'), ('state', 'Gujarat(Gandhinagar)'), ('state', 'Haryana(Chandigarh))'), ('state', 'Himachal Pradesh(Shimla)'), ('state', 'Jharkhand(Ranchi)'), ('state', 'Karnataka(Bangalore)'), ('state', 'Kerala(Thiruvananthapuram)'), ('state', 'Madhya Pradesh(Bhopal)'), ('state', 'Maharashtra(Mumbai)'), ('state', 'Manipur(Imphal)'), ('state', 'Meghalaya(Shillong)'), ('state', 'Mizoram(Aizawl)'), ('state', 'Nagaland(Kohima)'), ('state', 'Odisha(Bhubaneshwar)'), ('state', 'Punjab(Chandigarh)'), ('state', 'Rajasthan(Jaipur)'), ('state', 'Sikkim(Gangtok)'), ('state', 'Tamil Nadu(Chennai)'), ('state', 'Telangana(Hyderabad)'), ('state', 'Tripura(Agartala)'), ('state', 'Uttarakhand(Dehradun)'), ('state', 'Uttar Pradesh(Lucknow)'), ('state', 'West Bengal(Kolkata)'), ('union territories', ' Andaman and Nicobar Islands(Port Blair)'), ('union territories', ' Chandigarh(Chandigarh)'), ('union territories', 'Dadra and Nagar Haveli and Daman & Diu'), ('union territories', 'The Government of NCT of Delhi(Delhi)'), ('union territories', ' Jammu & Kashmir(Srinagar-S*, Jammu-W*)'), ('union territories', 'Ladakh(Leh)'), ('union territories', 'Lakshadweep(Kavaratti)'), ('union territories', ' Puducherry(Puducherry)')], default='West Bengal(Kolkata)', max_length=30)),
                ('Country', models.CharField(default='India', max_length=30)),
                ('Logo', models.ImageField(default='-', null=True, upload_to='')),
                ('Cover', models.ImageField(default='Null', upload_to='')),
                ('Admin', models.OneToOneField(default='-', on_delete=django.db.models.deletion.CASCADE, to='demoapp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='-', max_length=30)),
                ('Designation', models.CharField(default='-', max_length=600, null=True)),
                ('Mobile_No', models.CharField(default='-', max_length=10)),
                ('Join_In', models.DateField()),
                ('Till', models.DateField()),
                ('College', models.CharField(default='-', max_length=20, null=True)),
                ('Degree', models.CharField(default='-', max_length=30, null=True)),
                ('Specialization', models.CharField(default='-', max_length=90, null=True)),
                ('City', models.CharField(default='Siliguri', max_length=30)),
                ('States', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('state', 'Arunachal Pradesh(Itanagar)'), ('state', 'Assam(Dispur)'), ('state', 'Bihar(Patna)'), ('state', 'Chhattisgarh(Raipur)'), ('state', 'Goa(Panaji)'), ('state', 'Gujarat(Gandhinagar)'), ('state', 'Haryana(Chandigarh))'), ('state', 'Himachal Pradesh(Shimla)'), ('state', 'Jharkhand(Ranchi)'), ('state', 'Karnataka(Bangalore)'), ('state', 'Kerala(Thiruvananthapuram)'), ('state', 'Madhya Pradesh(Bhopal)'), ('state', 'Maharashtra(Mumbai)'), ('state', 'Manipur(Imphal)'), ('state', 'Meghalaya(Shillong)'), ('state', 'Mizoram(Aizawl)'), ('state', 'Nagaland(Kohima)'), ('state', 'Odisha(Bhubaneshwar)'), ('state', 'Punjab(Chandigarh)'), ('state', 'Rajasthan(Jaipur)'), ('state', 'Sikkim(Gangtok)'), ('state', 'Tamil Nadu(Chennai)'), ('state', 'Telangana(Hyderabad)'), ('state', 'Tripura(Agartala)'), ('state', 'Uttarakhand(Dehradun)'), ('state', 'Uttar Pradesh(Lucknow)'), ('state', 'West Bengal(Kolkata)'), ('union territories', ' Andaman and Nicobar Islands(Port Blair)'), ('union territories', ' Chandigarh(Chandigarh)'), ('union territories', 'Dadra and Nagar Haveli and Daman & Diu'), ('union territories', 'The Government of NCT of Delhi(Delhi)'), ('union territories', ' Jammu & Kashmir(Srinagar-S*, Jammu-W*)'), ('union territories', 'Ladakh(Leh)'), ('union territories', 'Lakshadweep(Kavaratti)'), ('union territories', ' Puducherry(Puducherry)')], default='West Bengal(Kolkata)', max_length=30)),
                ('Country', models.CharField(default='India', max_length=30)),
                ('Department', models.ManyToManyField(to='demoapp.Department')),
            ],
        ),
    ]
